import Head from "next/head";
import Script from "next/script";
import { useRouter } from "next/router";
import Image from "next/image";
import Button from "../../components/hoc/Buttons";
import Text from "../../components/hoc/Text";
export default function Home() {
  const router = useRouter();
  const path = router.asPath;
  return (
    <div className="bg-white">
      <Head>
        <title>100 Hour Yoga Teacher Training In Rishikesh, India</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">
        <header className="py-16">
          <section className="h-120 grid grid-cols-2 items-center px-32">
            <div className="flex flex-col  items-start uppercase">
              <div className="font-medium text-orange-600">home{path}</div>
              <div className="my-4 text-4xl font-semibold text-gray-800">
                100 Hour Yoga Teacher Training In Rishikesh, India
              </div>
              <div className="font-medium text-gray-600">
                Come and join us for the unforgettable experience of a lifetime
              </div>
              <Button>
                <div>Enroll Now</div>
              </Button>
            </div>
            <div className="flex justify-center">
              <Image
                height={500}
                width={500}
                alt="yoga in rishikesh"
                src="https://yinyangyogaacademy.com/wp-content/uploads/2022/09/Untitled-design.png"
              />
            </div>
          </section>
        </header>

        <main className="mx-32">
          {/* minus margin video section */}
          <section className=" mt-48 flex h-auto flex-col items-center bg-orange-600 text-white ">
            <video controls className="-mt-36 w-5/6">
              <source
                src="https://www.w3schools.com/html/mov_bbb.mp4"
                type="video/mp4"
              />
              Your browser does not support the video tag.
            </video>
            <div className="my-4 w-5/6">
              <div className="grid grid-cols-2 items-center">
                <div>
                  <div className="font-medium uppercase">
                    Authentic And Purest
                  </div>
                  <div className="my-4 text-4xl font-semibold">
                    100 Hour Yoga Teacher Training Rishikesh,India
                  </div>
                </div>
                <div className="font-medium">
                  The 100 Hour course is specially designed for novices and is a
                  breakdown of the 200 Hour YTTC. It is a two-week long,
                  complete immersion beginner course for individuals aspiring to
                  step into the world of Yoga and begin their journey.
                </div>
              </div>
              <div className="my-2 font-medium">
                The course focuses on expounding and strengthening the
                understanding of various basic concepts and fundamentals of Yoga
                and simultaneously helps you slow down, live in the present
                moment and connect to your true self, inspiring self-discovery
                on a physical and spiritual level.
              </div>
              <div className="my-8 font-medium">
                Backed by millennia of experience, our 100 Hour YTTC in
                Rishikesh is a perfect blend of both – theory and practice! With
                a range of subjects from Anatomy and Physiology, Yoga
                philosophy, Pranayama, Meditation, Sanskrit terminologies and
                Mantras to Asanas and Posture Integration, this course focuses
                on the fundamentals of Yoga, making it an ideal course for
                beginners. All through, we ensure a conducive environment
                dedicated to learning and growth.
              </div>
            </div>
          </section>
          {/* why teacher training explainer */}
          <section className="my-16">
            <div className="text-center">
              <Text.Secondary color="orange" size="lg">
                The Best Known
              </Text.Secondary>
              <div className="my-4">
                <Text.Primary color="black" size="lg">
                  100 Hour Yoga Teachers Training In Rishikesh
                </Text.Primary>
              </div>
            </div>
            <div className="grid grid-cols-3 space-x-12 text-center">
              <div className="flex flex-col items-center">
                <Image
                  height={200}
                  width={200}
                  alt="what is yoga"
                  src="https://yinyangyogaacademy.com/wp-content/uploads/2022/09/3-150x150.png"
                />
                <div className="my-4">
                  <Text.Secondary color="black" size="lg">
                    What Is Yoga?
                  </Text.Secondary>
                </div>

                <Text.Secondary color="gray" size="sm">
                  The 100 Hour Yoga Teacher Training in Rishikesh is a very
                  innovative module that is designed to help the students gain
                  the maximum skills with the use of theoretical, practical,
                  hypothetical, and intuitive knowledge in a safe and protected
                  environment.
                </Text.Secondary>
              </div>
              <div className="flex flex-col items-center">
                <Image
                  height={200}
                  width={200}
                  alt="what is yoga"
                  src="https://yinyangyogaacademy.com/wp-content/uploads/2022/09/3-150x150.png"
                />
                <div className="my-4">
                  <Text.Secondary color="black" size="lg">
                    What does this training give?
                  </Text.Secondary>
                </div>

                <Text.Secondary color="gray" size="sm">
                  The 100 Hour Yoga Teacher Training in Rishikesh is a very
                  innovative module that is designed to help the students gain
                  the maximum skills with the use of theoretical, practical,
                  hypothetical, and intuitive knowledge in a safe and protected
                  environment.
                </Text.Secondary>
              </div>

              <div className="flex flex-col items-center">
                <Image
                  height={200}
                  width={200}
                  alt="what is yoga"
                  src="https://yinyangyogaacademy.com/wp-content/uploads/2022/09/3-150x150.png"
                />
                <div className="my-4">
                  <Text.Secondary color="black" size="lg">
                    Why taking this training?
                  </Text.Secondary>
                </div>
                <Text.Secondary color="gray" size="sm">
                  The 100 Hour Yoga Teacher Training in Rishikesh is a very
                  innovative module that is designed to help the students gain
                  the maximum skills with the use of theoretical, practical,
                  hypothetical, and intuitive knowledge in a safe and protected
                  environment.
                </Text.Secondary>
              </div>
            </div>
          </section>
          {/* syllabus yoga */}
          <section className="my-32">
            <div className="grid grid-cols-3 items-center">
              <div>
                {[
                  {
                    title: "Anatomy & Physiology",
                    desc: "Deep insights into the inner workings of the human body",
                    image: "",
                  },
                  {
                    title: "Sanskrit",
                    desc: "Deep insights into the inner workings of the human body",
                    image: "",
                  },
                  {
                    title: "Asana Lab",
                    desc: "Deep insights into the inner workings of the human body",
                    image: "",
                  },
                  {
                    title: "Meditation",
                    desc: "Deep insights into the inner workings of the human body",
                    image: "",
                  },
                ].map((item, i) => {
                  return (
                    <div key={i} className="flex content-end items-center">
                      <div className="text-right">
                        <Text.Secondary size="lg">{item.title}</Text.Secondary>
                        <Text.Secondary color="gray">
                          {item.desc}
                        </Text.Secondary>
                      </div>
                      <div>
                        <Image
                          height={150}
                          width={150}
                          alt="what is yoga"
                          src="https://yinyangyogaacademy.com/wp-content/uploads/2022/09/3-150x150.png"
                        />
                      </div>
                    </div>
                  );
                })}
              </div>
              <div className="text-center">
                <Text.Primary size="lg">Course Syllabus</Text.Primary>
                <Image
                  height={500}
                  width={500}
                  alt="what is yoga"
                  src="https://yinyangyogaacademy.com/wp-content/uploads/2022/09/guruji.png"
                />
              </div>
              <div>
                {[
                  {
                    title: "Anatomy & Physiology",
                    desc: "Deep insights into the inner workings of the human body",
                    image: "",
                  },
                  {
                    title: "Sanskrit",
                    desc: "Deep insights into the inner workings of the human body",
                    image: "",
                  },
                  {
                    title: "Asana Lab",
                    desc: "Deep insights into the inner workings of the human body",
                    image: "",
                  },
                  {
                    title: "Meditation",
                    desc: "Deep insights into the inner workings of the human body",
                    image: "",
                  },
                ].map((item, i) => {
                  return (
                    <div key={i} className="flex items-center justify-start">
                      <div>
                        <Image
                          height={150}
                          width={150}
                          alt="what is yoga"
                          src="https://yinyangyogaacademy.com/wp-content/uploads/2022/09/3-150x150.png"
                        />
                      </div>
                      <div className="text-left ">
                        <Text.Secondary size="lg">{item.title}</Text.Secondary>
                        <Text.Secondary color="gray">
                          {item.desc}
                        </Text.Secondary>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
            <div className="text-center">
              <Text.Primary size="sm">
                100 Hour Yoga TTC In Rishikesh
              </Text.Primary>
            </div>
          </section>
        </main>

        <footer className="border-t border-gray-800 px-8 py-12">footer</footer>
      </div>
      <Script src="https://buttons.github.io/buttons.js" />
    </div>
  );
}
