import Head from "next/head";
import Script from "next/script";
import { useRouter } from "next/router";
import Image from "next/image";
import Button from "../../components/Buttons";
import Text from "../../components/Text";
import ReactPlayer from "react-player";
import Slider from "react-slick";
import { BsClockHistory } from "react-icons/bs";
import FAQ from "../../components/FAQ";
import Teacherprofile from "../../components/sections/Teacherprofile";
import { IoDownloadOutline } from "react-icons/io5";
import data from "../../data/data";

export default function Home() {
  const settingsBook = {
    dots: true,
    infinite: true,
    slidesToShow: 5,
    slidesToScroll: 3,
    cssEase: "linear",
    responsive: [
      {
        breakpoint: 1024,
        settings: {
          slidesToShow: 3,
          slidesToScroll: 3,
          infinite: true,
          dots: true,
        },
      },
      {
        breakpoint: 600,
        settings: {
          slidesToShow: 2,
          slidesToScroll: 2,
          initialSlide: 2,
        },
      },
      {
        breakpoint: 480,
        settings: {
          slidesToShow: 2,
          slidesToScroll: 2,
        },
      },
    ],
  };

  const settingsAccomodation = {
    infinite: true,
    slidesToShow: 4,
    slidesToScroll: 1,
    cssEase: "linear",
    autoplay: true,
    responsive: [
      {
        breakpoint: 480,
        settings: {
          slidesToShow: 1,
          slidesToScroll: 1,
        },
      },
    ],
  };
  const router = useRouter();
  const path = router.asPath;
  return (
    <div className="bg-white">
      <Head>
        <title>100 Hour Yoga Teacher Training In Rishikesh, India</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <header className=" courses-bg py-32">
          <section className="grid h-[60vh] grid-cols-2 items-center px-32">
            <div className="flex flex-col  items-start uppercase">
              <div className="font-medium text-orange-600">home{path}</div>
              <div className="my-4 text-4xl font-semibold text-gray-800">
                100 Hour Yoga Teacher Training In Rishikesh, India
              </div>
              <div className="font-medium text-gray-600">
                Come and join us for the unforgettable experience of a lifetime
              </div>
              <Button>
                <div>Enroll Now</div>
              </Button>
            </div>
            <div className="flex justify-center ">
              <Image
                height={500}
                width={500}
                alt="yoga in rishikesh"
                src="/courses-img.png"
              />
            </div>
          </section>
        </header>

        <main className=" my-24">
          {/* minus margin video section */}
          <section className=" mx-32 flex h-auto flex-col items-center justify-center bg-orange-600 text-white ">
            <div className="-mt-28 flex w-5/6 justify-center">
              <ReactPlayer url="https://youtu.be/I2aiSwHR1BE" />
            </div>
            <div className="my-4 w-5/6">
              <div className="grid grid-cols-2 items-center">
                <div>
                  <div className="font-medium uppercase">
                    Authentic And Purest
                  </div>
                  <div className="my-4 text-4xl font-semibold">
                    100 Hour Yoga Teacher Training Rishikesh,India
                  </div>
                </div>
                <div className="font-medium">
                  The 100 Hour course is specially designed for novices and is a
                  breakdown of the 200 Hour YTTC. It is a two-week long,
                  complete immersion beginner course for individuals aspiring to
                  step into the world of Yoga and begin their journey.
                </div>
              </div>
              <div className="my-2 font-medium">
                The course focuses on expounding and strengthening the
                understanding of various basic concepts and fundamentals of Yoga
                and simultaneously helps you slow down, live in the present
                moment and connect to your true self, inspiring self-discovery
                on a physical and spiritual level.
              </div>
              <div className="my-8 font-medium">
                Backed by millennia of experience, our 100 Hour YTTC in
                Rishikesh is a perfect blend of both – theory and practice! With
                a range of subjects from Anatomy and Physiology, Yoga
                philosophy, Pranayama, Meditation, Sanskrit terminologies and
                Mantras to Asanas and Posture Integration, this course focuses
                on the fundamentals of Yoga, making it an ideal course for
                beginners. All through, we ensure a conducive environment
                dedicated to learning and growth.
              </div>
            </div>
          </section>
          {/* why teacher training explainer */}
          <section className="bgCourses-left py-16 px-32">
            <div className="text-center">
              <div className="my-4">
                <h2 className="flex flex-col text-center text-[30px] font-bold md:text-[40px]">
                  100 Hour Yoga Teachers Training In Rishikesh
                  <span>
                    <Image
                      src="/underline.svg"
                      width={2500 / 12}
                      height={346 / 12}
                      alt="line-decor"
                    />{" "}
                  </span>
                </h2>
              </div>
            </div>
            <div className="grid grid-cols-3 space-x-12 text-center">
              <div className=" flex flex-col items-center space-y-4">
                <Image
                  height={64}
                  width={64}
                  alt="what is yoga"
                  src="/yoga-course.png"
                />
                <h3 className="text-lg font-semibold">What is Yoga </h3>

                <Text.Secondary color="gray" size="sm">
                  Yoga is the ancient art of achieving the oneness of the
                  internal with the external. It is the practice of
                  understanding the positive energies around us and using them
                  as a power. The 100 Hour Yoga Teacher Training in Rishikesh
                  seeks to provide around the experience of this art with the
                  help of experts and a tried-out and successful module
                  structure.
                </Text.Secondary>
              </div>
              <div className="flex flex-col items-center">
                <Image
                  height={64}
                  width={64}
                  alt="what is yoga"
                  src="/yoga-course-2.png"
                />
                <div className="my-4">
                  <h3 className="text-lg font-semibold">
                    What does this training give?
                  </h3>
                </div>

                <Text.Secondary color="gray" size="sm">
                  The 100 Hour Yoga Teacher Training in Rishikesh is a very
                  innovative module that is designed to help the students gain
                  the maximum skills with the use of theoretical, practical,
                  hypothetical, and intuitive knowledge in a safe and protected
                  environment.
                </Text.Secondary>
              </div>

              <div className="flex flex-col items-center">
                <Image
                  height={64}
                  width={64}
                  alt="what is yoga"
                  src="/yoga-course-3.png"
                />
                <div className="my-4">
                  <h3 className="text-lg font-semibold">
                    Why taking this training?
                  </h3>
                </div>
                <Text.Secondary color="gray" size="sm">
                  The 100 Hour Yoga Teacher Training in Rishikesh is a very
                  innovative module that is designed to help the students gain
                  the maximum skills with the use of theoretical, practical,
                  hypothetical, and intuitive knowledge in a safe and protected
                  environment. This course ensures that you learn the asanas to
                  perfection and are prepared to become a professional.
                </Text.Secondary>
              </div>
            </div>
          </section>
          {/* syllabus yoga */}
          <section className="wave  relative py-32 px-32">
            <h2 className="my-4 flex flex-col text-center text-[30px] font-bold md:text-[40px]">
              Course Syllabus
              <span>
                <Image
                  src="/underline.svg"
                  width={2500 / 12}
                  height={346 / 12}
                  alt="line-decor"
                />{" "}
              </span>
            </h2>
            <div className="grid grid-cols-3 items-center">
              <div>
                {[
                  {
                    title: "Anatomy & Physiology",
                    desc: "Deep insights into the inner workings of the human body",
                    image: "",
                  },
                  {
                    title: "Sanskrit",
                    desc: "Deep insights into the inner workings of the human body",
                    image: "",
                  },
                  {
                    title: "Asana Lab",
                    desc: "Deep insights into the inner workings of the human body",
                    image: "",
                  },
                  {
                    title: "Meditation",
                    desc: "Deep insights into the inner workings of the human body",
                    image: "",
                  },
                  {
                    title: "Restorative Yoga",
                    desc: " How to practice and teach restorative Yoga",
                    image: "",
                  },
                  {
                    title: "Chants and Mantra",
                    desc: "  Proper recitation of chants and mantras can transform energy in different areas of the body as well as improve concentration, memory and focus",
                    image: "",
                  },
                ].map((item, i) => {
                  return (
                    <div
                      key={i}
                      className="my-2 flex items-center justify-start space-x-4 rounded bg-white p-2 shadow-lg hover:bg-orange-400"
                    >
                      <div className=" w-1/4">
                        <Image
                          height={64}
                          width={64}
                          alt="what is yoga"
                          src="/buddhaIcon.png"
                        />
                      </div>
                      <div className="w-3/4 text-left ">
                        <Text.Secondary size="lg">{item.title}</Text.Secondary>
                        <Text.Secondary color="gray">
                          {item.desc}
                        </Text.Secondary>
                      </div>
                    </div>
                  );
                })}
              </div>
              <div className="text-center">
                <Text.Primary size="lg"></Text.Primary>
                <Image
                  height={500}
                  width={500}
                  alt="what is yoga"
                  src="https://yinyangyogaacademy.com/wp-content/uploads/2022/09/guruji.png"
                />
              </div>
              <div>
                {[
                  {
                    title: "Anatomy & Physiology",
                    desc: "Deep insights into the inner workings of the human body",
                    image: "",
                  },
                  {
                    title: "Sanskrit",
                    desc: "Deep insights into the inner workings of the human body",
                    image: "",
                  },
                  {
                    title: "Asana Lab",
                    desc: "Deep insights into the inner workings of the human body",
                    image: "",
                  },
                  {
                    title: "Meditation",
                    desc: "Deep insights into the inner workings of the human body",
                    image: "",
                  },
                  {
                    title: "Restorative Yoga",
                    desc: " How to practice and teach restorative Yoga",
                    image: "",
                  },
                  {
                    title: "Chants and Mantra",
                    desc: "  Proper recitation of chants and mantras can transform energy in different areas of the body as well as improve concentration, memory and focus",
                    image: "",
                  },
                ].map((item, i) => {
                  return (
                    <div
                      key={i}
                      className="my-2 flex items-center justify-start space-x-4 rounded bg-white p-2 shadow-lg hover:bg-orange-400"
                    >
                      <div className="w-1/4">
                        <Image
                          height={64}
                          width={64}
                          alt="what is yoga"
                          src="/buddhaIcon.png"
                        />
                      </div>
                      <div className="w-3/4 text-left ">
                        <Text.Secondary size="lg">{item.title}</Text.Secondary>
                        <Text.Secondary color="gray">
                          {item.desc}
                        </Text.Secondary>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
            <div className="flex justify-center">
              <div className="my-4 w-1/3 bg-orange-600 p-4 text-center font-semibold text-white ">
                Detailed Syllabus
              </div>
            </div>
          </section>
          <section className="px-32 py-16 ">
            <h2 className="my-4 flex flex-col text-center text-[30px] font-bold md:text-[40px]">
              Accomodation &amp; Food
              <span>
                <Image
                  src="/underline.svg"
                  width={2500 / 12}
                  height={346 / 12}
                  alt="line-decor"
                />
              </span>
            </h2>
            <div className="grid grid-cols-3 gap-4">
              <div className="flex items-center space-x-4 rounded p-4 shadow-md">
                <Image src="/simpleA.png" height={64} width={64} alt="simple" />
                <p>Simple and clean accommodation</p>
              </div>
              <div className="flex items-center space-x-4 rounded p-4 shadow-md">
                <Image src="/simpleB.png" height={64} width={64} alt="simple" />
                <p>
                  Accommodation comprises single rooms and double shared rooms.
                </p>
              </div>{" "}
              <div className="flex items-center space-x-4 rounded p-4 shadow-md">
                <Image src="/simpleC.png" height={64} width={64} alt="simple" />
                <p>
                  The bathrooms are equipped with western toilet seats and cold
                  showers
                </p>
              </div>{" "}
              <div className="flex items-center space-x-4 rounded p-4 shadow-md">
                <Image src="/simpleD.png" height={64} width={64} alt="simple" />
                <p>
                  Three highly nutritious, pure vegetarian meals per day
                  (breakfast, lunch, dinner).
                </p>
              </div>{" "}
              <div className="flex items-center space-x-4 rounded p-4 shadow-md">
                <Image src="/simpleE.png" height={64} width={64} alt="simple" />
                <p>Refreshing herbal tea is also provided every morning.</p>
              </div>
              <div className="flex items-center space-x-4 rounded p-4 shadow-md">
                <Image src="/simpleF.png" height={64} width={64} alt="simple" />
                <p>24 hours RO-filtered drinking water.</p>
              </div>
            </div>
            <div className="overflow-x-hidden py-16 ">
              <Slider {...settingsAccomodation}>
                {[
                  "https://www.yogkulam.org/images/acc/ryk-1.jpg",
                  "https://www.yogkulam.org/images/acc/ryk-4.jpg",
                  "https://www.yogkulam.org/images/acc/ryk-5.jpg",
                  "https://www.yogkulam.org/images/acc/ryk-2.jpg",
                  "https://www.yogkulam.org/images/acc/ryk-1.jpg",
                  "https://www.yogkulam.org/images/acc/ryk-4.jpg",
                  "https://www.yogkulam.org/images/acc/ryk-5.jpg",
                  "https://www.yogkulam.org/images/acc/ryk-2.jpg",
                ].map((item, index) => {
                  return (
                    <div key={index}>
                      <Image src={item} height={300} width={400} alt={item} />
                    </div>
                  );
                })}
              </Slider>
            </div>
            <div>
              <blockquote>
                <span className="text-lg font-semibold italic ">
                  Important Note:{" "}
                </span>
                <br />
                Absenting oneself from the scheduled program without prior
                permission of the teacher or manager concerned would be
                construed as a gross breach of discipline. <br />
                Private accommodation and Air conditioning facilities are
                available at an additional cost.
              </blockquote>
            </div>
          </section>
          {/* Section Time Table  */}

          <section className="floralChakra px-32 py-16">
            <h2 className="my-4 flex flex-col text-center text-[30px] font-bold md:text-[40px]">
              100 Hour Yoga Teacher Training In Rishikesh - Daily Schedule
              <span>
                <Image
                  src="/underline.svg"
                  width={2500 / 12}
                  height={346 / 12}
                  alt="line-decor"
                />
              </span>
            </h2>
            <p className="text-center text-lg">
              100 Hour Yoga Teacher Training is specially designed to keep the
              student in contemplation of the subject matter throughout the day
              while also allowing them personal time. This schedule is the best
              integration of theory and practice, helping the student stay fresh
              and energetic throughout the day.
            </p>

            <div className="my-4 grid grid-cols-5 gap-3">
              {[
                {
                  activity: "MORNING BELL",
                  time: "5:30 AM",
                  icon: "/iconA.png",
                },
                {
                  activity: "HATHA YOGA	",
                  time: "6:00 to 7:30 AM",
                  icon: "/iconB.png",
                },
                {
                  activity: "PRANAYAMA",
                  time: "7:45 to 8:45 AM",
                  icon: "/iconC.png",
                },
                {
                  activity: "BREAKFAST",
                  time: "8:45 to 9:45AM",
                  icon: "/iconD.png",
                },
                {
                  activity: "YOGA PHILOSOPHY",
                  time: "10:00 TO 11:00AM",
                  icon: "/iconsE.png",
                },
                {
                  activity: "ALIGNMENT AND ADJUSTMENT",
                  time: "11:15 to 12:15PM",
                  icon: "/iconA.png",
                },
                {
                  activity: "YOGA ANATOMY AND PHYSIOLOGY",
                  time: "12:30 to 1:30PM",
                  icon: "/iconA.png",
                },
                {
                  activity: "LUNCH",
                  time: "1:30 to 2:30PM",
                  icon: "/iconA.png",
                },
                {
                  activity: "REST",
                  time: "2:30 to 4:30PM",
                  icon: "/iconA.png",
                },
                {
                  activity: "ASHTANGA VINYASA",
                  time: "4:30 to 6:00 PM",
                  icon: "/iconA.png",
                },
                {
                  activity: "MEDITATION",
                  time: "6:15 to 7:15 PM",
                  icon: "/iconA.png",
                },
                {
                  activity: "DINNER",
                  time: "7:30 to 8:30 PM",
                  icon: "/iconA.png",
                },
                {
                  activity: "LIGHTS OFF",
                  time: "9:00 PM",
                  icon: "/iconA.png",
                },
              ].map((item, index) => {
                return (
                  <div
                    key={index}
                    className="rounded border-t-4 bg-white  shadow shadow-orange-200 hover:border-[#bd0006]"
                  >
                    <div className="flex items-center space-x-3 p-4">
                      <Image
                        src={item.icon}
                        height={40}
                        width={40}
                        alt="activity"
                      />
                      <p className="text-md font-semibold">{item.activity}</p>
                    </div>
                    <div className=" flex w-full space-x-4 bg-slate-300 p-4 hover:bg-[#bd0006]">
                      <BsClockHistory size={20} color="white" />
                      <p className="italic text-white"> {item.time}</p>
                    </div>
                  </div>
                );
              })}
            </div>
            <div className="w-1/3 rounded bg-white p-4 shadow-lg">
              <span className="text-xl font-bold text-[#bd0006] ">Note</span>
              <p>Schedule is subjected to change.</p>
            </div>
          </section>
          {/* Important Instructions */}
          <section className="px-32 py-16">
            <h2 className="my-4 flex flex-col text-center text-[30px] font-bold md:text-[40px]">
              Important Instructions and Notices for Students
              <span>
                <Image
                  src="/underline.svg"
                  width={2500 / 12}
                  height={346 / 12}
                  alt="line-decor"
                />
              </span>
            </h2>
            <ul className="space-y-4">
              <li className="flex items-center space-x-4">
                <Image
                  src="/icons-home/001-chakra.png"
                  width={30}
                  height={30}
                  alt="bullet"
                />
                <span>
                  Discipline is an integral part of the training program and so
                  the course routine must be strictly observed.
                </span>
              </li>
              <li className="flex w-full items-center space-x-4">
                <Image
                  src="/icons-home/001-chakra.png"
                  width={30}
                  height={30}
                  alt="bullet"
                  className="w-1/6"
                />
                <span className="w-5/6">
                  All classes are mandatory. Only in case of an emergency or
                  illness can one take leave with the respected teacher’s
                  permission. Uninformed leaves won’t be accepted, will be
                  considered a gross breach of discipline and will affect the
                  student’s monthly performance.
                </span>
              </li>{" "}
              <li className="flex items-center space-x-4">
                <Image
                  src="/icons-home/001-chakra.png"
                  width={30}
                  height={30}
                  alt="bullet"
                />
                <span>
                  Ensure you are on time for class since you will not be
                  permitted to enter any class once it has commenced.
                </span>
              </li>{" "}
              <li className="flex items-center space-x-4">
                <Image
                  src="/icons-home/001-chakra.png"
                  width={30}
                  height={30}
                  alt="bullet"
                />
                <span>
                  Disobeying the rules and regulations could result in
                  termination of studentship with no refund of fees.
                </span>
              </li>{" "}
              <li className="flex items-center space-x-4">
                <Image
                  src="/icons-home/001-chakra.png"
                  width={30}
                  height={30}
                  alt="bullet"
                />
                <span>
                  A student must give advance intimation if they intend to skip
                  a meal so that there is no wastage of food.
                </span>
              </li>
              <li className="flex items-center space-x-4">
                <Image
                  src="/icons-home/001-chakra.png"
                  width={30}
                  height={30}
                  alt="bullet"
                />
                <span>
                  Rishikesh Yogkulam does not make arrangements for guests of
                  students. Any activity that is not related to the course is
                  not permitted.
                </span>
              </li>
              <li className="flex items-center space-x-4">
                <Image
                  src="/icons-home/001-chakra.png"
                  width={30}
                  height={30}
                  alt="bullet"
                />
                <span>
                  Smoking and alcohol are not permitted during the training.
                </span>
              </li>
            </ul>
          </section>
          {/* Evaluation and Certification */}
          <section className="px-32 py-16">
            <h2 className="my-4 flex flex-col text-center text-[30px] font-bold md:text-[40px]">
              Evaluation And Certification
              <span>
                <Image
                  src="/underline.svg"
                  width={2500 / 12}
                  height={346 / 12}
                  alt="line-decor"
                />
              </span>
            </h2>
            <ul className="space-y-4">
              <li className="flex items-center space-x-4">
                <Image
                  src="/icons-home/001-chakra.png"
                  width={30}
                  height={30}
                  alt="bullet"
                />
                <span>
                  Assessments will be based on written as well as practical
                  evaluation.
                </span>
              </li>
              <li className="flex w-full items-center space-x-4">
                <Image
                  src="/icons-home/001-chakra.png"
                  width={30}
                  height={30}
                  alt="bullet"
                  className="w-1/6"
                />
                <span className="w-5/6">
                  A student&apos;s conduct will be a part of the assessment
                  criteria.
                </span>
              </li>{" "}
              <li className="flex items-center space-x-4">
                <Image
                  src="/icons-home/001-chakra.png"
                  width={30}
                  height={30}
                  alt="bullet"
                />
                <span>
                  Evaluation will be carried out only for those students who
                  have a minimum of 90% attendance.
                </span>
              </li>
              <li className="flex items-center space-x-4">
                <Image
                  src="/icons-home/001-chakra.png"
                  width={30}
                  height={30}
                  alt="bullet"
                />
                <span>
                  Upon successful assessment, the student will receive a
                  certificate accredited by Yoga Alliance, USA.
                </span>
              </li>
            </ul>
          </section>
          {/* Eligibilty */}
          <section className="px-32 py-16">
            <h2 className="flex flex-col text-center text-[30px] font-bold md:text-[40px]">
              Eligibility Criterion
              <span>
                <Image
                  src="/underline.svg"
                  width={2500 / 12}
                  height={346 / 12}
                  alt="line-decor"
                />{" "}
              </span>
            </h2>
            <p>
              The only prerequisite for our students is that they have an open
              mind and a thirst for learning and growth. At least 6 months of
              practice is recommended (though not required). Upon acceptance to
              the course, the student is expected to be present for every class
              and complete the coursework diligently.
            </p>
            <div className="mt-4 flex items-center justify-between rounded bg-white p-4 shadow-lg">
              <h3 className="text-[30px] font-semibold">
                Total Course Fee for 100 hours YTTC
              </h3>
              <span className="bg-[#bd0006] p-4 text-[30px] font-semibold text-white">
                USD 499
              </span>
            </div>
          </section>

          <section className="px-32 py-16 ">
            <h2 className="my-4 flex flex-col text-center text-[30px] font-bold md:text-[40px]">
              Frequently Asked Questions
              <span>
                <Image
                  src="/underline.svg"
                  width={2500 / 12}
                  height={346 / 12}
                  alt="line-decor"
                />
              </span>
            </h2>
            <FAQ />
          </section>
          <div className=" w-full px-8 py-4 md:px-32 md:py-16">
            <h3 className="mb-8 text-[26px] md:text-[40px] ">
              Find The Best Yoga Books Here
              <div className="h-1 w-[10%] bg-orange-500"></div>
            </h3>

            <Slider {...settingsBook}>
              {data.books.map((item, index) => {
                return (
                  <div key={index} className="h-full p-4">
                    <div className="relative">
                      <Image
                        src={item.image}
                        layout="responsive"
                        height={240}
                        width={140}
                        alt="book"
                      />
                      <div className="absolute bottom-0 flex w-full flex-col items-center justify-center bg-black p-4 text-center text-white opacity-75">
                        <p className="hidden text-sm md:block md:text-lg">
                          {item.title}
                        </p>
                        <p className=" hidden text-sm md:block md:text-base">
                          -<em>{item.author}</em>
                        </p>
                        <label
                          htmlFor="my-modal"
                          className="modal-button btn m-4 flex bg-orange-600  px-2 py-1 text-[12px] md:space-x-4 md:px-4 md:py-2"
                        >
                          <IoDownloadOutline color="white" />
                          <span>Download</span>
                        </label>
                      </div>
                    </div>
                  </div>
                );
              })}
            </Slider>

            {/* Modal Box opens here  */}
            <input type="checkbox" id="my-modal" className="modal-toggle" />
            <div className="modal">
              <div className="modal-box relative">
                <label
                  htmlFor="my-modal"
                  className="btn btn-circle btn-sm absolute right-2 top-2 bg-orange-600"
                >
                  ✕
                </label>
                <h4 className="my-4 text-[24px] font-semibold">
                  Fill this Form To Download the Book
                </h4>
                <form className="space-y-4">
                  <div className="form-control w-full">
                    <label className="label">
                      <span className="label-text">Your Name</span>
                    </label>
                    <input
                      type="text"
                      placeholder="Type here"
                      className="input input-bordered w-full "
                    />
                    <label className="label">
                      <span className="label-text">Your Email</span>
                    </label>
                    <input
                      type="text"
                      placeholder="Type here"
                      className="input input-bordered w-full"
                    />
                  </div>
                  <button className="btn btn-xs bg-orange-600 sm:btn-sm md:btn-md lg:btn-md">
                    Get PDF
                  </button>
                </form>
              </div>
            </div>
          </div>

          {/* Teacher Profile */}
          <Teacherprofile />
        </main>
      </div>
    </div>
  );
}
